# SPDX-License-Identifier: GPL-2.0+
#
# Makefile - ASUS ROG Ally handheld device driver
#
asus-ally-hid-y := asus-ally-hid-core.o asus-ally-rgb.o asus-ally-hid-input.o asus-ally-hid-config.o
obj-$(CONFIG_ASUS_ALLY_HID) := asus-ally-hid.o
