# SPDX-License-Identifier: GPL-2.0+
#
# Makefile - Zotac Zone handheld device driver
#
zotac-zone-hid-y := zotac-zone-hid-core.o zotac-zone-hid-rgb.o zotac-zone-hid-input.o zotac-zone-hid-config.o
obj-$(CONFIG_ZOTAC_ZONE_HID) := zotac-zone-hid.o
