# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the ntfs3 filesystem support.
#

obj-$(CONFIG_NTFS3_FS) += ntfs3.o

ntfs3-objs := bitfunc.o bitmap.o inode.o fsntfs.o frecord.o \
	    index.o attrlist.o record.o attrib.o run.o xattr.o\
	    upcase.o super.o file.o dir.o namei.o lznt.o\
	    fslog.o
